### ISSUE TITLE
Split Repo

### ISSUE THREAD

**Issue by reiner-dolp** [liblouis/liblouis-js#26]
Splitting the repository into two repositories:

__1. Repo: liblouis-js__ Main repository, contains documentation, build scripts and the easy-api  (which only wraps official liblouis builds and makes them usable)
__2. Repo: liblouis-js-build__ only contains builds of liblouis that were cross compiled to js. Each official release of the C-API has a commit in this repo adding at least one cross compiled build of the C-API release. Each commit in this repo is tagged with the version of the C-API using git.

Currently, end users automatically recieve the latest build of the C-API that I created, when they obtain liblouis-js through their package manager. e.g.

```js
npm install liblouis-js 
```

With split repositories, users can select one or several specific versions of the C-API and obtain the latest and most stable version of the easy-api:

```
npm install liblouis-js-build@3.0.0
npm install liblouis-js
```
If the user did not explicilty install a liblouis build, `npm install liblouis-js` could automatically obtain the latest release through dependency management.

A `package.json` using two different liblouis builds with the latest easy-API:

```js
{
  "dependencies": {
    "liblouis_v300": "liblouis/js-build#v3.0.0",
    "liblouis_v310": "liblouis/js-build#v3.1.0",
    "liblouis-js": "latest"
  }
}
```
Build switching with this configuration:

```js
const v300= require('liblouis_v300');
const v310= require('liblouis_v310');
const liblouis = require('liblouis');

liblouis.setLiblouisBuild(v300);
// do stuff with liblouis v3.0.0
liblouis.setLiblouisBuild(v310);
// do stuff with liblouis v3.1.0
```

**Comment by reiner-dolp** [comment]
`liblouis` and `liblouis-build` would actually be better package names:

```
npm install liblouis-build@3.0.0
npm install liblouis
```

**Comment by reiner-dolp** [comment]
@bertfrees can I get a repo called `js-build`?

**Comment by bertfrees** [comment]
Sure. But first some questions:

- Wouldn't some versions of liblouis be incompatible with some versions of liblouis-build?
- Could the js-build repo be automatically populated by Travis?
- Could the liblouis package, in theory, live in a subdirectory of the main liblouis repo?

**Comment by reiner-dolp** [comment]
- the easy-API only breaks if the function signature of a `lou_*` function changes. (This will only break the corresponding easy-API function, all functions with unchanged signatures will still work.) Adding new `lou_*` functions will not break anything.
- Automatic population by Travis would be amazing.  Currently I am just executing the [commands listed in the README](https://github.com/liblouis/liblouis-js#compiling-the-latest-version-of-liblouis) by hand.
- (The short answer to this is *maybe*, remainder are some thoughts) I am currently trying to support two package managers: `npm` and `bower`. npm is unaware of git when packages are published. Everything in the CWD not blacklisted by a ignore file is part of the release. Therefore it would work for `npm`. (Just create a subfolder and `cd`+`npm publish` when you want to. This is however a detail most javascript/npm users will not be aware of, which will lead to confusion and silly issue reports in the bug tracker. Its customary to tag and publish as bower does automatically.) Bower is pulling the meta information directly from git: each tagged commit is a release/publish to the package registry. Therefore each release would contain a huge pile of unnecessary garbage. (Also: the main repository would have to move to [semantic versioning](http://semver.org/), which would be nearly impossible since simple table patches could require a major version jump from e.g. `3.0.0` to `4.0.0`.)

Why do you want to integrate everything in a single repository? If you just want the javascript API to be available when the repo is cloned, we could simply add a `package.json` that lists `liblouis-js` as dependency.

**Comment by reiner-dolp** [comment]
Just noticed that the build switching example does not work as intended. npm fails to clone two different versions of the same dependency. [There are several workarounds](https://github.com/npm/npm/issues/5499). E.g.

```json
{
  "dependencies": {
    "liblouis-build-v3-0-0": "latest",
    "liblouis-build-v3-1-0": "latest",
    "liblouis-js": "latest"
}
```

or: 

```
npm install liblouis
npm run fetchLiblouisBuild 3.0.0
npm run fetchLiblouisBuild 3.1.0
```

```js
{
  "dependencies": {
    "liblouis-js": "latest"
  }

  "scripts": {
      "fetchLiblouisBuild": "... npm install liblouis-build@$VERSION && cd node_modules && mv liblouis-build liblouis_v300 ..."
  }
}
```

**Comment by bertfrees** [comment]
> Automatic population by Travis would be amazing.  Currently I am just executing the [commands listed in the README](https://github.com/liblouis/liblouis-js#compiling-the-latest-version-of-liblouis) by hand.

I'll try to integrate these commands in our [`.travis.yml`](https://github.com/liblouis/liblouis/blob/master/.travis.yml). For every commit on master "liblouis.js" could be updated in liblouis-js-build, and in addition for every new tag we can copy that tag to liblouis-js-build.

> Why do you want to integrate everything in a single repository?

Like I said, just for maintenance reasons. If there is one repository there are less things to think about. For example, if a change in the C code causes a problem js part, you notice immediately when you make the change.

If it's not possible, that's fine. I'm just asking these questions to understand things better.

> If you just want the javascript API to be available when the repo is cloned, we could simply add a `package.json` that lists `liblouis-js` as dependency.

I don't think that is my intention, no.

> Can I get a repo called `js-build`?

Is it OK if we use the name that you originally chose, "liblouis-js-build"?

**Comment by bertfrees** [comment]
One last question: the copy of the tables directory: in which repository would it live after the split?

**Comment by reiner-dolp** [comment]
Currently each release of `liblouis-js` bundles two builds of liblouis:
- the file `liblouis-tables-embeded.js` which is: emscriptens c runtime + liblouis + a virtual file system that resides in RAM, containing all table files (thats why the file huge, about 30M which takes about 2-4s to load)
- the file `liblouis-no-tables.js` : emscriptens c runtime + liblouis + an empty virtual file system. The easy-api detects failed table accesses, loads the file from a location defined by `liblouis.enableOnDemandFile()`, writes it to the virtual file system and retries the table read.

`liblouis-tables-embeded.js` is easy great for testing, as you just have to include the file and it works. It is however bad for production given the load time. `liblouis-no-tables.js` is harder to use (you have to spin up a web worker -- which is a thread that can only communicate via message passing) but better for production usage as it loads faster and does not block the GUI thread of a web page.

Variants I like:
- table files live in their own repository (a third repository) that could be accessed with `npm install liblouis-tables@3.1.0`.
- We could add a method `npm run fetchTables 3.0.0` similar to the `npm run fetchLiblouisBuild 3.0.0` approach above.
- We could make the tables part of each tagged commit in the `js-build` repo. Tables being part of the `liblouis-js` repo does not make sense.

**Comment by reiner-dolp** [comment]
`js-build` is nicer than `liblouis-js-build` as users have to mention the github organisation name in some circumstances. Therefore you get `liblouis/js-build` instead of `liblouis/liblouis-js-build`.

**Comment by bertfrees** [comment]
> We could make the tables part of each tagged commit in the `js-build` repo.

This makes the most sense right now I think. Splitting the tables in a separate repository would probably be the ideal situation, but I don't think it's feasible at the moment because Liblouis tables often depend on a specific version of the code. Splitting the tables would mean we would have to provide some kind of compatibility matrix.
